# Generated by Django 5.2.4 on 2025-07-22 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
        ("tags", "0002_alter_tag_unique_together_tag_unique_user_tag_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="timeblock",
            new_name="idx_user_date",
            old_name="dashboard_t_user_id_52517b_idx",
        ),
        migrations.RenameIndex(
            model_name="timeblock",
            new_name="idx_user_tag",
            old_name="dashboard_t_user_id_63ed85_idx",
        ),
        migrations.AlterUniqueTogether(
            name="timeblock",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="timeblock",
            index=models.Index(fields=["date", "slot_index"], name="idx_date_slot"),
        ),
        migrations.AddConstraint(
            model_name="timeblock",
            constraint=models.UniqueConstraint(
                fields=("user", "date", "slot_index"),
                name="unique_user_date_slot",
                violation_error_message="해당 시간대에 이미 기록이 존재합니다.",
            ),
        ),
    ]
